### PR TITLE
Map key can be any comparable type now

### PR DESCRIPTION
**Pull request by niandy**

### CODE REVIEW

**Comment by mastertheknife** [comment]
I would like to see this feature merged.
The map key being string only is what currently prevents me from using this library.

**Comment by fufuok** [comment]
I see it has not been updated for a long time. Maybe these are useful to you:

**Comment by jackgene** [comment]
Curious if there are any reasons not to merge this? Performance? API?

I really like this feature, and I realize I can just fork @niandy's implementation and change the module name, but I also wanted to make sure you don't have any concerns with this implementation.

**Comment by xiaoyaoking** [comment]
This is very good

**Comment by orcaman** [comment]
Thanks guys. I'll take a look and hopefully merge today

**Comment by orcaman** [comment]
@jackgene @mastertheknife  @niandy  can you please describe a use case for a non-string key? 

I get what the capability adds flexibility, but I'm not sure about it. Consider redis which only supports string keys (by design). Isn't non-string keys an anti-pattern?

**Comment by mastertheknife** [comment]
Sure, i use non-string keys it all the time.
For example in a connection tracking project that deals with conntrack, i have a struct that i use as a map key, 5 tuple to match the kernel's 5 tuple.
```
type ConnKey struct {
	Src      netip.Addr
	Dst      netip.Addr
	SrcPort  uint16 // In case of ICMP, this contains the ICMP ID
	DstPort  uint16 // In case of ICMP, this contains the type & code (Low byte: type, High byte: code)
	Protocol uint8
}
connmap := make(map[ConnKey]ConnData)
```

Another example:
```remotes := make(map[netip.AddrPort]RemoteData)```

**Comment by orcaman** [comment]
Thanks @mastertheknife. I have to say that I'm not a fan of implicit keys in map-type data structures, but since the native map in go now supports that, it only makes sense that our map allow this. I'll merge this soon

**Comment by orcaman** [comment]
Merged. Note new release version

**Comment by jackgene** [comment]
> Thanks @mastertheknife. I have to say that I'm not a fan of implicit keys in map-type data structures, but since the native map in go now supports that, it only makes sense that our map allow this. I'll merge this soon

Thanks for merging. But I just wanted to point something out, you mentioned:
> since the native map in go now supports that

Implying this is new. It is not. Go `map` has always supported keys of any `comparable` type. This is from Go 1.0 as far as I know.

It's also not an anti-pattern at all, and something common to all major programming languages: [Java](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html) (and by extension all JVM languages), [Rust](https://doc.rust-lang.org/std/collections/struct.HashMap.html), [Python](https://docs.python.org/3.6/library/typing.html#typing.Dict), [C#](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=net-7.0). Etc. The only language that kind of encourages string-only keys is Javascript (and even then, it's allowed, just that you may have trouble with certain operations - e.g., converting to JSON).

**Comment by orcaman** [comment]
Thanks @jackgene

**Pull request merged**
