### PR TITLE
Support for 1.18 generics

### PR DESCRIPTION
**Pull request by ImVexed**
Hello!

I found myself beginning to port some personal projects to 1.18 and found that this library didn't yet have any support for generics. So, I figured I might as well take a swing at it.

I'm not exactly sure what the right path is for making this available is since 1.18 is still a beta. Regardless, hopefully this is useful to others :)

### CODE REVIEW

**Comment by orcaman** [comment]
This is very cool. I am looking forward to reviewing this soon

**Comment by chbomtempo** [comment]
@ImVexed You missed the .travis.yml file.

**Comment by ImVexed** [comment]
> @ImVexed You missed the .travis.yml file.

Not particularly sure what's failing now or why.

**Comment by chbomtempo** [comment]
Seems that golangci-lint have some issues with 1.18... https://github.com/google/go-github/issues/2296

**Comment by soulmachine** [comment]
any updates? Looking forward to generics support

**Comment by ImVexed** [comment]
@chbomtempo seems to be working fine now that 1.18 is out

**Comment by orcaman** [comment]
Thanks @ImVexed , you rock.

**Pull request merged**
